sorting/sorting/urls.py
from django.contrib import admin
from django.urls import path, include
from sortingApp.views import HomeView, BubbleView, SelectionView, InsertionView, MergeView, QuickView, RadixView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view()),
    path('sortingApp/',include('sortingApp.urls',namespace='bubble')),
    path('sortingApp/',include('sortingApp.urls',namespace='selection')),
    path('sortingApp/',include('sortingApp.urls',namespace='insertion')),
    path('sortingApp/',include('sortingApp.urls',namespace='merge')),
    path('sortingApp/',include('sortingApp.urls',namespace='quick')),
    path('sortingApp/',include('sortingApp.urls',namespace='radix')),
]

sorting/sortingApp/urls.py
from django.urls import path
from sortingApp.views import HomeView, BubbleView, SelectionView, InsertionView, MergeView, QuickView, RadixView
app_name = 'sortingApp'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('bubble/', BubbleView.as_view(), name='bubble'),
    path('insertion/', InsertionView.as_view(), name='insertion'),
    path('selection/', SelectionView.as_view(), name='selection'),
    path('merge/', MergeView.as_view(), name='merge'),
    path('quick/', QuickView.as_view(), name='quick'),
    path('radix/', RadixView.as_view(), name='radix'),
]

sorting/sortingApp/models.py
from django.db import models

# Create your models here.

sorting/sortingApp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'sortingApp/home.html'

class BubbleView(TemplateView):
    template_name = 'sortingApp/bubble.html'

class SelectionView(TemplateView):
    template_name = 'sortingApp/selection.html'

class InsertionView(TemplateView):
    template_name = 'sortingApp/insertion.html'

class MergeView(TemplateView):
    template_name = 'sortingApp/merge.html'

class QuickView(TemplateView):
    template_name = 'sortingApp/quick.html'

class RadixView(TemplateView):
    template_name = 'sortingApp/radix.html'

sorting/sortingApp/templates/sortingApp/bubble.html
{% extends "sortingApp/home.html" %}

{% block content %}
    <h2>Time and Space Complexity Analysis</h2>
    <ul>
        <li>
            <h4>Time Complexity: O(n*n)</h4>
                <ul>
                    <li><p>O(n*n). Worst case scenario when input array is completely unsorted.</p></li>
                    <li><p>O(n). Best case scenario when input array is fully sorted. The nested loop will only have to perform one single pass.</p></li>
                </ul>
        </li>
        <li>
            <h4>Space Complexity: O(1)</h4>
            <ul>
                <li><p>Bubble Sort is a constant space, O(1), algorithm. The amount of memory consumed by the algorithm does not increase relative to the size of the input array.</p></li>
            </ul>
        </li>
        <li>
            <h4>When should we use Bubble Sort?</h4>
            <ul>
                <li><p>When sorting really small arrays where run time will be negligible no matter what algorithm we choose.</p></li>
                <li><p>When sorting arrays that we expect to already be nearly sorted.</p></li>
            </ul>
        </li>
    </ul>
{% endblock content %}

sorting/sortingApp/templates/sortingApp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Sorting Algorithms</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'sortingApp:home' %}">Home</a>
        <a class="navbar-brand" href="{% url 'sortingApp:bubble' %}">Bubble Sort</a>
        <a class="navbar-brand" href="{% url 'sortingApp:selection' %}">Selection Sort</a>
        <a class="navbar-brand" href="{% url 'sortingApp:insertion' %}">Insertion Sort</a>
        <a class="navbar-brand" href="{% url 'sortingApp:merge' %}">Merge Sort</a>
        <a class="navbar-brand" href="{% url 'sortingApp:quick' %}">Quick Sort</a>
        <a class="navbar-brand" href="{% url 'sortingApp:radix' %}">Radix Sort</a>
    </nav>

    <div class="jumbotron">
        {% block content %}
          
        {% endblock content %}
    </div>
</body>
</html>

sorting/sortingApp/templates/sortingApp/insertion.html
{% extends "sortingApp/home.html" %}

{% block content %}
    <h2>Time and Space Complexity Analysis</h2>
    <ul>
        <li>
            <h4>Time Complexity: O(n*n)</h4>
                <ul>
                    <li><p>The two loops are nested so our total time complexity is O(n * n / 2) = O(n2).</p></li>
                </ul>
        </li>
        <li>
            <h4>Space Complexity: O(1)</h4>
            <ul>
                <li><p>The amount of memory consumed by the algorithm does not increase relative to the size of the input array.</p></li>
            </ul>
        </li>
        <li>
            <h4>When should we use Bubble Sort?</h4>
            <ul>
                <li><p>There only one case where insertion sort is better than bubble sort. Is when the cost swapping elements are not expensive.</p></li>
            </ul>
        </li>
    </ul>
{% endblock content %}

sorting/sortingApp/templates/sortingApp/merge.html
{% extends "sortingApp/home.html" %}

{% block content %}
    <h2>Time and Space Complexity Analysis</h2>
    <ul>
        <li>
            <h4>Time Complexity: O(n log(n))</h4>
                <ul>
                    <li><p>n is the length of the input array.</p></li>
                    <li><p>Log n is how many recursive calls we make. Since we split the array in half, the number of recursive calls is O(log(n)).</p></li>
                </ul>
        </li>
        <li>
            <h4>Space Complexity: O(1)</h4>
            <ul>
                <li><p>The larger the size of our input array, the greater the number of subarrays we must create in memory.Therefore, Merge Sort has a linear space complexity, O(n).</p></li>
            </ul>
        </li>
        <li>
            <h4>When should we use Bubble Sort?</h4>
            <ul>
                <li><p>We have unlimited memory available.</p></li>
            </ul>
        </li>
    </ul>
{% endblock content %}

sorting/sortingApp/templates/sortingApp/quick.html
{% extends "sortingApp/home.html" %}

{% block content %}
        <h2>Time and Space Complexity Analysis</h2>
    <ul>
        <li>
            <h4>Time Complexity: O(n log(n))</h4>
                <ul>
                    <li><p>Average Case: O(n log(n)). When we chose a random pivot.</p></li>
                    <li><p>Worst Case: O(n*n). When we chose the worst pivot.</p></li>
                    <li><p>Best Case: O(nlog(n)). When we chose the median pivot.</p></li>
                </ul>
        </li>
        <li>
            <h4>Space Complexity: O(1)</h4>
            <ul>
                <li><p>Our implementation of quickSort uses O(n) space because of the partition arrays we create. Note: There is also another version uses O(log(n)) space.</p></li>
            </ul>
        </li>
        <li>
            <h4>When should we use Bubble Sort?</h4>
            <ul>
                <li><p>The recursive code is light and simple to implement than merge sort.</p></li>
                <li><p>When we know the constrain of data set. Since the algorithm allows us to pick the pivot anywhere in the array.</p></li>
            </ul>
        </li>
    </ul>
{% endblock content %}

sorting/sortingApp/templates/sortingApp/radix.html
{% extends "sortingApp/home.html" %}

{% block content %}
    <h2>Time and Space Complexity Analysis</h2>
    <ul>
        <li>
            <h4>Time Complexity: O(n*k) k is the length (number of digits)</h4>
                <ul>
                    <li><p>In general, the best, average, and worst case time complexities of Radix Sort are all the same.</p></li>
                    <li><p>Note:  There exists a camp that believes that when Radix Sort's input array contains entirely unique values, due to a characteristic of the way computers store numerical data, that k becomes log k. (See Wikipedia: Radix Sort)</p></li>
                </ul>
        </li>
        <li>
            <h4>Space Complexity: O(n + k) k is the length (number of digits</h4>
            <ul>
                <li><p>The amount of memory consumed by the algorithm increases relative to both the size of the input array and the length of the longest integer.</p></li>
            </ul>
        </li>
        <li>
            <h4>When should we use Bubble Sort?</h4>
            <ul>
                <li><p>Sort a list of any sort of binary data, including numeric, text, or image data in binary format.</p></li>
                <li><p>Sort a list of integers, and you don't know the value of the largest element in the list.</p></li>
            </ul>
        </li>
    </ul>
{% endblock content %}

sorting/sortingApp/templates/sortingApp/selection.html
{% extends "sortingApp/home.html" %}

{% block content %}
    <h2>Time and Space Complexity Analysis</h2>
    <ul>
        <li>
            <h4>Time Complexity: O(n*n)</h4>
                <ul>
                    <li><p>O(n*n). Worst case scenario where our input array is entirely unsorted, since this algorithm contains a nested loop, its run time behaves similarly to bubbleSort and selectionSor</p></li>
                    <li><p>O(n). Best case scenario where our left side of the array is always sorted.</p></li>
                </ul>
        </li>
        <li>
            <h4>Space Complexity: O(1)</h4>
            <ul>
                <li><p>The amount of memory consumed by the algorithm does not increase relative to the size of the input array.</p></li>
            </ul>
        </li>
        <li>
            <h4>When should we use Bubble Sort?</h4>
            <ul>
                <li><p>The absolute best case scenario for Insertion Sort is when there is only one unsorted element, and it is located all the way to the right of the array. (Online Algorithm)</p></li>
            </ul>
        </li>
    </ul>
{% endblock content %}